/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : coherence.sm
 */

#include "coherence.h"
#include "./coherence_sm.h"

#define getOwner(fsm) \
    (fsm)->_owner

#define POPULATE_STATE(state) \
    state##_MESI, \
    state##_MESIF, \
    state##_MOESI, \
    state##_MOSI, \
    state##_MSI, \
    state##_a_del, \
    state##_a_modify, \
    state##_a_read, \
    state##_i_del, \
    state##_i_modify, \
    state##_i_read, \
    state##_Default

#define ENTRY_STATE(state)

#define EXIT_STATE(state)

static void coherenceState_MESI(struct coherenceContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_MESIF(struct coherenceContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_MOESI(struct coherenceContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_MOSI(struct coherenceContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_MSI(struct coherenceContext *fsm)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{
    getState(fsm)->Default(fsm);
}

static void coherenceState_Default(struct coherenceContext *fsm)
{
    if (getDebugFlag(fsm) != 0) {
        TRACE("TRANSITION   : %s.%s\n", getName(getState(fsm)), getTransition(fsm));
    }
    State_Default(fsm);
}

#define Init_Start_MESI coherenceState_MESI
#define Init_Start_MESIF coherenceState_MESIF
#define Init_Start_MOESI coherenceState_MOESI
#define Init_Start_MOSI coherenceState_MOSI
#define Init_Start_MSI coherenceState_MSI
#define Init_Start_a_del coherenceState_a_del
#define Init_Start_a_modify coherenceState_a_modify
#define Init_Start_a_read coherenceState_a_read
#define Init_Start_i_del coherenceState_i_del
#define Init_Start_i_modify coherenceState_i_modify
#define Init_Start_i_read coherenceState_i_read
#define Init_Start_Default coherenceState_Default
#define Init_Start_Entry NULL
#define Init_Start_Exit NULL
#define Init_DefaultState_MESI coherenceState_MESI
#define Init_DefaultState_MESIF coherenceState_MESIF
#define Init_DefaultState_MOESI coherenceState_MOESI
#define Init_DefaultState_MOSI coherenceState_MOSI
#define Init_DefaultState_MSI coherenceState_MSI
#define Init_DefaultState_a_del coherenceState_a_del
#define Init_DefaultState_a_modify coherenceState_a_modify
#define Init_DefaultState_a_read coherenceState_a_read
#define Init_DefaultState_i_del coherenceState_i_del
#define Init_DefaultState_i_modify coherenceState_i_modify
#define Init_DefaultState_i_read coherenceState_i_read

#undef Init_Start_MESI
static void Init_Start_MESI(struct coherenceContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : Init_Start)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: Init_&Init_Start.MESI()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : Init_&Init_Start.MESI()\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef Init_Start_MESIF
static void Init_Start_MESIF(struct coherenceContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : Init_Start)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: Init_&Init_Start.MESIF()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : Init_&Init_Start.MESIF()\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef Init_Start_MOESI
static void Init_Start_MOESI(struct coherenceContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : Init_Start)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: Init_&Init_Start.MOESI()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : Init_&Init_Start.MOESI()\n");
    }
    setState(fsm, &MOESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef Init_Start_MOSI
static void Init_Start_MOSI(struct coherenceContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : Init_Start)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: Init_&Init_Start.MOSI()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : Init_&Init_Start.MOSI()\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef Init_Start_MSI
static void Init_Start_MSI(struct coherenceContext *fsm)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : Init_Start)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: Init_&Init_Start.MSI()\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : Init_&Init_Start.MSI()\n");
    }
    setState(fsm, &MSI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState Init_Start = { POPULATE_STATE(Init_Start), 0, "Init_Start" };

#define MSI_I_MESI coherenceState_MESI
#define MSI_I_MESIF coherenceState_MESIF
#define MSI_I_MOESI coherenceState_MOESI
#define MSI_I_MOSI coherenceState_MOSI
#define MSI_I_MSI coherenceState_MSI
#define MSI_I_a_del coherenceState_a_del
#define MSI_I_a_modify coherenceState_a_modify
#define MSI_I_a_read coherenceState_a_read
#define MSI_I_i_del coherenceState_i_del
#define MSI_I_i_modify coherenceState_i_modify
#define MSI_I_i_read coherenceState_i_read
#define MSI_I_Default coherenceState_Default
#define MSI_I_Entry NULL
#define MSI_I_Exit NULL
#define MSI_M_MESI coherenceState_MESI
#define MSI_M_MESIF coherenceState_MESIF
#define MSI_M_MOESI coherenceState_MOESI
#define MSI_M_MOSI coherenceState_MOSI
#define MSI_M_MSI coherenceState_MSI
#define MSI_M_a_del coherenceState_a_del
#define MSI_M_a_modify coherenceState_a_modify
#define MSI_M_a_read coherenceState_a_read
#define MSI_M_i_del coherenceState_i_del
#define MSI_M_i_modify coherenceState_i_modify
#define MSI_M_i_read coherenceState_i_read
#define MSI_M_Default coherenceState_Default
#define MSI_M_Entry NULL
#define MSI_M_Exit NULL
#define MSI_S_MESI coherenceState_MESI
#define MSI_S_MESIF coherenceState_MESIF
#define MSI_S_MOESI coherenceState_MOESI
#define MSI_S_MOSI coherenceState_MOSI
#define MSI_S_MSI coherenceState_MSI
#define MSI_S_a_del coherenceState_a_del
#define MSI_S_a_modify coherenceState_a_modify
#define MSI_S_a_read coherenceState_a_read
#define MSI_S_i_del coherenceState_i_del
#define MSI_S_i_modify coherenceState_i_modify
#define MSI_S_i_read coherenceState_i_read
#define MSI_S_Default coherenceState_Default
#define MSI_S_Entry NULL
#define MSI_S_Exit NULL
#define MSI_DefaultState_MESI coherenceState_MESI
#define MSI_DefaultState_MESIF coherenceState_MESIF
#define MSI_DefaultState_MOESI coherenceState_MOESI
#define MSI_DefaultState_MOSI coherenceState_MOSI
#define MSI_DefaultState_MSI coherenceState_MSI
#define MSI_DefaultState_a_del coherenceState_a_del
#define MSI_DefaultState_a_modify coherenceState_a_modify
#define MSI_DefaultState_a_read coherenceState_a_read
#define MSI_DefaultState_i_del coherenceState_i_del
#define MSI_DefaultState_i_modify coherenceState_i_modify
#define MSI_DefaultState_i_read coherenceState_i_read

#undef MSI_I_i_read
#define MSI_I_i_read MSI_DefaultState_i_read
#undef MSI_M_i_read
#define MSI_M_i_read MSI_DefaultState_i_read
#undef MSI_S_i_read
#define MSI_S_i_read MSI_DefaultState_i_read
#undef MSI_DefaultState_i_read
static void MSI_DefaultState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.i_read(n, i, l)\n");
    }
}

#undef MSI_I_i_modify
#define MSI_I_i_modify MSI_DefaultState_i_modify
#undef MSI_M_i_modify
#define MSI_M_i_modify MSI_DefaultState_i_modify
#undef MSI_S_i_modify
#define MSI_S_i_modify MSI_DefaultState_i_modify
#undef MSI_DefaultState_i_modify
static void MSI_DefaultState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.i_modify(n, i, l)\n");
    }
}

#undef MSI_I_i_del
#define MSI_I_i_del MSI_DefaultState_i_del
#undef MSI_M_i_del
#define MSI_M_i_del MSI_DefaultState_i_del
#undef MSI_S_i_del
#define MSI_S_i_del MSI_DefaultState_i_del
#undef MSI_DefaultState_i_del
static void MSI_DefaultState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.i_del(n, i, l)\n");
    }
}

#undef MSI_I_a_read
#define MSI_I_a_read MSI_DefaultState_a_read
#undef MSI_M_a_read
#define MSI_M_a_read MSI_DefaultState_a_read
#undef MSI_S_a_read
#define MSI_S_a_read MSI_DefaultState_a_read
#undef MSI_DefaultState_a_read
static void MSI_DefaultState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.a_read(n, i, l)\n");
    }
}

#undef MSI_I_a_modify
#define MSI_I_a_modify MSI_DefaultState_a_modify
#undef MSI_M_a_modify
#define MSI_M_a_modify MSI_DefaultState_a_modify
#undef MSI_S_a_modify
#define MSI_S_a_modify MSI_DefaultState_a_modify
#undef MSI_DefaultState_a_modify
static void MSI_DefaultState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.a_modify(n, i, l)\n");
    }
}

#undef MSI_I_a_del
#define MSI_I_a_del MSI_DefaultState_a_del
#undef MSI_M_a_del
#define MSI_M_a_del MSI_DefaultState_a_del
#undef MSI_S_a_del
#define MSI_S_a_del MSI_DefaultState_a_del
#undef MSI_DefaultState_a_del
static void MSI_DefaultState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_DefaultState.a_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_DefaultState.a_del(n, i, l)\n");
    }
}

#undef MSI_I_i_modify
static void MSI_I_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_I)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_I.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_I.i_modify(n, i, l)\n");
    }
    setState(fsm, &MSI_M);
    ENTRY_STATE(getState(fsm));
}

#undef MSI_I_i_read
static void MSI_I_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_I)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_I.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_I.i_read(n, i, l)\n");
    }
    setState(fsm, &MSI_S);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MSI_I = { POPULATE_STATE(MSI_I), 1, "MSI_I" };

#undef MSI_M_i_del
static void MSI_M_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_M.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_M.i_del(n, i, l)\n");
    }
    setState(fsm, &MSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MSI_M_i_modify
static void MSI_M_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_M.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_M.i_modify(n, i, l)\n");
    }
    setState(fsm, &MSI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MSI_M = { POPULATE_STATE(MSI_M), 2, "MSI_M" };

#undef MSI_S_a_modify
static void MSI_S_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_S.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_S.a_modify(n, i, l)\n");
    }
    setState(fsm, &MSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MSI_S_a_read
static void MSI_S_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_S.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_S.a_read(n, i, l)\n");
    }
    setState(fsm, &MSI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MSI_S_i_del
static void MSI_S_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MSI_&MSI_S.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MSI_&MSI_S.i_del(n, i, l)\n");
    }
    setState(fsm, &MSI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MSI_S = { POPULATE_STATE(MSI_S), 3, "MSI_S" };

#define MESI_I_MESI coherenceState_MESI
#define MESI_I_MESIF coherenceState_MESIF
#define MESI_I_MOESI coherenceState_MOESI
#define MESI_I_MOSI coherenceState_MOSI
#define MESI_I_MSI coherenceState_MSI
#define MESI_I_a_del coherenceState_a_del
#define MESI_I_a_modify coherenceState_a_modify
#define MESI_I_a_read coherenceState_a_read
#define MESI_I_i_del coherenceState_i_del
#define MESI_I_i_modify coherenceState_i_modify
#define MESI_I_i_read coherenceState_i_read
#define MESI_I_Default coherenceState_Default
#define MESI_I_Entry NULL
#define MESI_I_Exit NULL
#define MESI_M_MESI coherenceState_MESI
#define MESI_M_MESIF coherenceState_MESIF
#define MESI_M_MOESI coherenceState_MOESI
#define MESI_M_MOSI coherenceState_MOSI
#define MESI_M_MSI coherenceState_MSI
#define MESI_M_a_del coherenceState_a_del
#define MESI_M_a_modify coherenceState_a_modify
#define MESI_M_a_read coherenceState_a_read
#define MESI_M_i_del coherenceState_i_del
#define MESI_M_i_modify coherenceState_i_modify
#define MESI_M_i_read coherenceState_i_read
#define MESI_M_Default coherenceState_Default
#define MESI_M_Entry NULL
#define MESI_M_Exit NULL
#define MESI_S_MESI coherenceState_MESI
#define MESI_S_MESIF coherenceState_MESIF
#define MESI_S_MOESI coherenceState_MOESI
#define MESI_S_MOSI coherenceState_MOSI
#define MESI_S_MSI coherenceState_MSI
#define MESI_S_a_del coherenceState_a_del
#define MESI_S_a_modify coherenceState_a_modify
#define MESI_S_a_read coherenceState_a_read
#define MESI_S_i_del coherenceState_i_del
#define MESI_S_i_modify coherenceState_i_modify
#define MESI_S_i_read coherenceState_i_read
#define MESI_S_Default coherenceState_Default
#define MESI_S_Entry NULL
#define MESI_S_Exit NULL
#define MESI_E_MESI coherenceState_MESI
#define MESI_E_MESIF coherenceState_MESIF
#define MESI_E_MOESI coherenceState_MOESI
#define MESI_E_MOSI coherenceState_MOSI
#define MESI_E_MSI coherenceState_MSI
#define MESI_E_a_del coherenceState_a_del
#define MESI_E_a_modify coherenceState_a_modify
#define MESI_E_a_read coherenceState_a_read
#define MESI_E_i_del coherenceState_i_del
#define MESI_E_i_modify coherenceState_i_modify
#define MESI_E_i_read coherenceState_i_read
#define MESI_E_Default coherenceState_Default
#define MESI_E_Entry NULL
#define MESI_E_Exit NULL
#define MESI_DefaultState_MESI coherenceState_MESI
#define MESI_DefaultState_MESIF coherenceState_MESIF
#define MESI_DefaultState_MOESI coherenceState_MOESI
#define MESI_DefaultState_MOSI coherenceState_MOSI
#define MESI_DefaultState_MSI coherenceState_MSI
#define MESI_DefaultState_a_del coherenceState_a_del
#define MESI_DefaultState_a_modify coherenceState_a_modify
#define MESI_DefaultState_a_read coherenceState_a_read
#define MESI_DefaultState_i_del coherenceState_i_del
#define MESI_DefaultState_i_modify coherenceState_i_modify
#define MESI_DefaultState_i_read coherenceState_i_read

#undef MESI_I_i_read
#define MESI_I_i_read MESI_DefaultState_i_read
#undef MESI_M_i_read
#define MESI_M_i_read MESI_DefaultState_i_read
#undef MESI_S_i_read
#define MESI_S_i_read MESI_DefaultState_i_read
#undef MESI_E_i_read
#define MESI_E_i_read MESI_DefaultState_i_read
#undef MESI_DefaultState_i_read
static void MESI_DefaultState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.i_read(n, i, l)\n");
    }
}

#undef MESI_I_i_modify
#define MESI_I_i_modify MESI_DefaultState_i_modify
#undef MESI_M_i_modify
#define MESI_M_i_modify MESI_DefaultState_i_modify
#undef MESI_S_i_modify
#define MESI_S_i_modify MESI_DefaultState_i_modify
#undef MESI_E_i_modify
#define MESI_E_i_modify MESI_DefaultState_i_modify
#undef MESI_DefaultState_i_modify
static void MESI_DefaultState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.i_modify(n, i, l)\n");
    }
}

#undef MESI_I_i_del
#define MESI_I_i_del MESI_DefaultState_i_del
#undef MESI_M_i_del
#define MESI_M_i_del MESI_DefaultState_i_del
#undef MESI_S_i_del
#define MESI_S_i_del MESI_DefaultState_i_del
#undef MESI_E_i_del
#define MESI_E_i_del MESI_DefaultState_i_del
#undef MESI_DefaultState_i_del
static void MESI_DefaultState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.i_del(n, i, l)\n");
    }
}

#undef MESI_I_a_read
#define MESI_I_a_read MESI_DefaultState_a_read
#undef MESI_M_a_read
#define MESI_M_a_read MESI_DefaultState_a_read
#undef MESI_S_a_read
#define MESI_S_a_read MESI_DefaultState_a_read
#undef MESI_E_a_read
#define MESI_E_a_read MESI_DefaultState_a_read
#undef MESI_DefaultState_a_read
static void MESI_DefaultState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.a_read(n, i, l)\n");
    }
}

#undef MESI_I_a_modify
#define MESI_I_a_modify MESI_DefaultState_a_modify
#undef MESI_M_a_modify
#define MESI_M_a_modify MESI_DefaultState_a_modify
#undef MESI_S_a_modify
#define MESI_S_a_modify MESI_DefaultState_a_modify
#undef MESI_E_a_modify
#define MESI_E_a_modify MESI_DefaultState_a_modify
#undef MESI_DefaultState_a_modify
static void MESI_DefaultState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.a_modify(n, i, l)\n");
    }
}

#undef MESI_I_a_del
#define MESI_I_a_del MESI_DefaultState_a_del
#undef MESI_M_a_del
#define MESI_M_a_del MESI_DefaultState_a_del
#undef MESI_S_a_del
#define MESI_S_a_del MESI_DefaultState_a_del
#undef MESI_E_a_del
#define MESI_E_a_del MESI_DefaultState_a_del
#undef MESI_DefaultState_a_del
static void MESI_DefaultState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_DefaultState.a_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_DefaultState.a_del(n, i, l)\n");
    }
}

#undef MESI_I_i_modify
static void MESI_I_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_I)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_I.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_I.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_M);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_I_i_read
static void MESI_I_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_I)\n");
    }
    if (exist_somewhere() == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESI_&MESI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESI_&MESI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MESI_S);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESI_&MESI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESI_&MESI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MESI_E);
        ENTRY_STATE(getState(fsm));
    }    else {
        MESI_DefaultState_i_read(fsm, n, i, l);
    }
}

const struct coherenceState MESI_I = { POPULATE_STATE(MESI_I), 4, "MESI_I" };

#undef MESI_M_a_modify
static void MESI_M_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_M.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_M.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_M_a_read
static void MESI_M_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_M.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_M.a_read(n, i, l)\n");
    }
    setState(fsm, &MESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_M_i_del
static void MESI_M_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_M.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_M.i_del(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESI_M = { POPULATE_STATE(MESI_M), 5, "MESI_M" };

#undef MESI_S_a_modify
static void MESI_S_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_S.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_S.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_S_i_del
static void MESI_S_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_S.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_S.i_del(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_S_i_modify
static void MESI_S_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_S.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_S.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESI_S = { POPULATE_STATE(MESI_S), 6, "MESI_S" };

#undef MESI_E_a_modify
static void MESI_E_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_E.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_E.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_E_a_read
static void MESI_E_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_E.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_E.a_read(n, i, l)\n");
    }
    setState(fsm, &MESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_E_i_del
static void MESI_E_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_E.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_E.i_del(n, i, l)\n");
    }
    setState(fsm, &MESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESI_E_i_modify
static void MESI_E_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESI_&MESI_E.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESI_&MESI_E.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESI_E = { POPULATE_STATE(MESI_E), 7, "MESI_E" };

#define MOSI_I_MESI coherenceState_MESI
#define MOSI_I_MESIF coherenceState_MESIF
#define MOSI_I_MOESI coherenceState_MOESI
#define MOSI_I_MOSI coherenceState_MOSI
#define MOSI_I_MSI coherenceState_MSI
#define MOSI_I_a_del coherenceState_a_del
#define MOSI_I_a_modify coherenceState_a_modify
#define MOSI_I_a_read coherenceState_a_read
#define MOSI_I_i_del coherenceState_i_del
#define MOSI_I_i_modify coherenceState_i_modify
#define MOSI_I_i_read coherenceState_i_read
#define MOSI_I_Default coherenceState_Default
#define MOSI_I_Entry NULL
#define MOSI_I_Exit NULL
#define MOSI_M_MESI coherenceState_MESI
#define MOSI_M_MESIF coherenceState_MESIF
#define MOSI_M_MOESI coherenceState_MOESI
#define MOSI_M_MOSI coherenceState_MOSI
#define MOSI_M_MSI coherenceState_MSI
#define MOSI_M_a_del coherenceState_a_del
#define MOSI_M_a_modify coherenceState_a_modify
#define MOSI_M_a_read coherenceState_a_read
#define MOSI_M_i_del coherenceState_i_del
#define MOSI_M_i_modify coherenceState_i_modify
#define MOSI_M_i_read coherenceState_i_read
#define MOSI_M_Default coherenceState_Default
#define MOSI_M_Entry NULL
#define MOSI_M_Exit NULL
#define MOSI_S_MESI coherenceState_MESI
#define MOSI_S_MESIF coherenceState_MESIF
#define MOSI_S_MOESI coherenceState_MOESI
#define MOSI_S_MOSI coherenceState_MOSI
#define MOSI_S_MSI coherenceState_MSI
#define MOSI_S_a_del coherenceState_a_del
#define MOSI_S_a_modify coherenceState_a_modify
#define MOSI_S_a_read coherenceState_a_read
#define MOSI_S_i_del coherenceState_i_del
#define MOSI_S_i_modify coherenceState_i_modify
#define MOSI_S_i_read coherenceState_i_read
#define MOSI_S_Default coherenceState_Default
#define MOSI_S_Entry NULL
#define MOSI_S_Exit NULL
#define MOSI_O_MESI coherenceState_MESI
#define MOSI_O_MESIF coherenceState_MESIF
#define MOSI_O_MOESI coherenceState_MOESI
#define MOSI_O_MOSI coherenceState_MOSI
#define MOSI_O_MSI coherenceState_MSI
#define MOSI_O_a_del coherenceState_a_del
#define MOSI_O_a_modify coherenceState_a_modify
#define MOSI_O_a_read coherenceState_a_read
#define MOSI_O_i_del coherenceState_i_del
#define MOSI_O_i_modify coherenceState_i_modify
#define MOSI_O_i_read coherenceState_i_read
#define MOSI_O_Default coherenceState_Default
#define MOSI_O_Entry NULL
#define MOSI_O_Exit NULL
#define MOSI_DefaultState_MESI coherenceState_MESI
#define MOSI_DefaultState_MESIF coherenceState_MESIF
#define MOSI_DefaultState_MOESI coherenceState_MOESI
#define MOSI_DefaultState_MOSI coherenceState_MOSI
#define MOSI_DefaultState_MSI coherenceState_MSI
#define MOSI_DefaultState_a_del coherenceState_a_del
#define MOSI_DefaultState_a_modify coherenceState_a_modify
#define MOSI_DefaultState_a_read coherenceState_a_read
#define MOSI_DefaultState_i_del coherenceState_i_del
#define MOSI_DefaultState_i_modify coherenceState_i_modify
#define MOSI_DefaultState_i_read coherenceState_i_read

#undef MOSI_I_i_read
#define MOSI_I_i_read MOSI_DefaultState_i_read
#undef MOSI_M_i_read
#define MOSI_M_i_read MOSI_DefaultState_i_read
#undef MOSI_S_i_read
#define MOSI_S_i_read MOSI_DefaultState_i_read
#undef MOSI_O_i_read
#define MOSI_O_i_read MOSI_DefaultState_i_read
#undef MOSI_DefaultState_i_read
static void MOSI_DefaultState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.i_read(n, i, l)\n");
    }
}

#undef MOSI_I_i_modify
#define MOSI_I_i_modify MOSI_DefaultState_i_modify
#undef MOSI_M_i_modify
#define MOSI_M_i_modify MOSI_DefaultState_i_modify
#undef MOSI_S_i_modify
#define MOSI_S_i_modify MOSI_DefaultState_i_modify
#undef MOSI_O_i_modify
#define MOSI_O_i_modify MOSI_DefaultState_i_modify
#undef MOSI_DefaultState_i_modify
static void MOSI_DefaultState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.i_modify(n, i, l)\n");
    }
}

#undef MOSI_I_i_del
#define MOSI_I_i_del MOSI_DefaultState_i_del
#undef MOSI_M_i_del
#define MOSI_M_i_del MOSI_DefaultState_i_del
#undef MOSI_S_i_del
#define MOSI_S_i_del MOSI_DefaultState_i_del
#undef MOSI_O_i_del
#define MOSI_O_i_del MOSI_DefaultState_i_del
#undef MOSI_DefaultState_i_del
static void MOSI_DefaultState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.i_del(n, i, l)\n");
    }
}

#undef MOSI_I_a_read
#define MOSI_I_a_read MOSI_DefaultState_a_read
#undef MOSI_M_a_read
#define MOSI_M_a_read MOSI_DefaultState_a_read
#undef MOSI_S_a_read
#define MOSI_S_a_read MOSI_DefaultState_a_read
#undef MOSI_O_a_read
#define MOSI_O_a_read MOSI_DefaultState_a_read
#undef MOSI_DefaultState_a_read
static void MOSI_DefaultState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.a_read(n, i, l)\n");
    }
}

#undef MOSI_I_a_modify
#define MOSI_I_a_modify MOSI_DefaultState_a_modify
#undef MOSI_M_a_modify
#define MOSI_M_a_modify MOSI_DefaultState_a_modify
#undef MOSI_S_a_modify
#define MOSI_S_a_modify MOSI_DefaultState_a_modify
#undef MOSI_O_a_modify
#define MOSI_O_a_modify MOSI_DefaultState_a_modify
#undef MOSI_DefaultState_a_modify
static void MOSI_DefaultState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.a_modify(n, i, l)\n");
    }
}

#undef MOSI_I_a_del
#define MOSI_I_a_del MOSI_DefaultState_a_del
#undef MOSI_M_a_del
#define MOSI_M_a_del MOSI_DefaultState_a_del
#undef MOSI_S_a_del
#define MOSI_S_a_del MOSI_DefaultState_a_del
#undef MOSI_O_a_del
#define MOSI_O_a_del MOSI_DefaultState_a_del
#undef MOSI_DefaultState_a_del
static void MOSI_DefaultState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_DefaultState.a_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_DefaultState.a_del(n, i, l)\n");
    }
}

#undef MOSI_I_i_modify
static void MOSI_I_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_I)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_I.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_I.i_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_M);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_I_i_read
static void MOSI_I_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_I)\n");
    }
    if (exist_somewhere() == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOSI_&MOSI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOSI_&MOSI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MOSI_S);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOSI_&MOSI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOSI_&MOSI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MOSI_O);
        ENTRY_STATE(getState(fsm));
    }    else {
        MOSI_DefaultState_i_read(fsm, n, i, l);
    }
}

const struct coherenceState MOSI_I = { POPULATE_STATE(MOSI_I), 8, "MOSI_I" };

#undef MOSI_M_a_modify
static void MOSI_M_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_M.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_M.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_M_a_read
static void MOSI_M_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_M.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_M.a_read(n, i, l)\n");
    }
    setState(fsm, &MOSI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_M_i_del
static void MOSI_M_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_M.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_M.i_del(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOSI_M = { POPULATE_STATE(MOSI_M), 9, "MOSI_M" };

#undef MOSI_S_a_modify
static void MOSI_S_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_S.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_S.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_S_i_del
static void MOSI_S_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_S.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_S.i_del(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_S_i_modify
static void MOSI_S_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_S.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_S.i_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOSI_S = { POPULATE_STATE(MOSI_S), 10, "MOSI_S" };

#undef MOSI_O_a_modify
static void MOSI_O_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_O)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_O.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_O.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_O_i_del
static void MOSI_O_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_O)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_O.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_O.i_del(n, i, l)\n");
    }
    setState(fsm, &MOSI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOSI_O_i_modify
static void MOSI_O_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOSI_O)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOSI_&MOSI_O.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOSI_&MOSI_O.i_modify(n, i, l)\n");
    }
    setState(fsm, &MOSI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOSI_O = { POPULATE_STATE(MOSI_O), 11, "MOSI_O" };

#define MOESI_I_MESI coherenceState_MESI
#define MOESI_I_MESIF coherenceState_MESIF
#define MOESI_I_MOESI coherenceState_MOESI
#define MOESI_I_MOSI coherenceState_MOSI
#define MOESI_I_MSI coherenceState_MSI
#define MOESI_I_a_del coherenceState_a_del
#define MOESI_I_a_modify coherenceState_a_modify
#define MOESI_I_a_read coherenceState_a_read
#define MOESI_I_i_del coherenceState_i_del
#define MOESI_I_i_modify coherenceState_i_modify
#define MOESI_I_i_read coherenceState_i_read
#define MOESI_I_Default coherenceState_Default
#define MOESI_I_Entry NULL
#define MOESI_I_Exit NULL
#define MOESI_M_MESI coherenceState_MESI
#define MOESI_M_MESIF coherenceState_MESIF
#define MOESI_M_MOESI coherenceState_MOESI
#define MOESI_M_MOSI coherenceState_MOSI
#define MOESI_M_MSI coherenceState_MSI
#define MOESI_M_a_del coherenceState_a_del
#define MOESI_M_a_modify coherenceState_a_modify
#define MOESI_M_a_read coherenceState_a_read
#define MOESI_M_i_del coherenceState_i_del
#define MOESI_M_i_modify coherenceState_i_modify
#define MOESI_M_i_read coherenceState_i_read
#define MOESI_M_Default coherenceState_Default
#define MOESI_M_Entry NULL
#define MOESI_M_Exit NULL
#define MOESI_S_MESI coherenceState_MESI
#define MOESI_S_MESIF coherenceState_MESIF
#define MOESI_S_MOESI coherenceState_MOESI
#define MOESI_S_MOSI coherenceState_MOSI
#define MOESI_S_MSI coherenceState_MSI
#define MOESI_S_a_del coherenceState_a_del
#define MOESI_S_a_modify coherenceState_a_modify
#define MOESI_S_a_read coherenceState_a_read
#define MOESI_S_i_del coherenceState_i_del
#define MOESI_S_i_modify coherenceState_i_modify
#define MOESI_S_i_read coherenceState_i_read
#define MOESI_S_Default coherenceState_Default
#define MOESI_S_Entry NULL
#define MOESI_S_Exit NULL
#define MOESI_E_MESI coherenceState_MESI
#define MOESI_E_MESIF coherenceState_MESIF
#define MOESI_E_MOESI coherenceState_MOESI
#define MOESI_E_MOSI coherenceState_MOSI
#define MOESI_E_MSI coherenceState_MSI
#define MOESI_E_a_del coherenceState_a_del
#define MOESI_E_a_modify coherenceState_a_modify
#define MOESI_E_a_read coherenceState_a_read
#define MOESI_E_i_del coherenceState_i_del
#define MOESI_E_i_modify coherenceState_i_modify
#define MOESI_E_i_read coherenceState_i_read
#define MOESI_E_Default coherenceState_Default
#define MOESI_E_Entry NULL
#define MOESI_E_Exit NULL
#define MOESI_O_MESI coherenceState_MESI
#define MOESI_O_MESIF coherenceState_MESIF
#define MOESI_O_MOESI coherenceState_MOESI
#define MOESI_O_MOSI coherenceState_MOSI
#define MOESI_O_MSI coherenceState_MSI
#define MOESI_O_a_del coherenceState_a_del
#define MOESI_O_a_modify coherenceState_a_modify
#define MOESI_O_a_read coherenceState_a_read
#define MOESI_O_i_del coherenceState_i_del
#define MOESI_O_i_modify coherenceState_i_modify
#define MOESI_O_i_read coherenceState_i_read
#define MOESI_O_Default coherenceState_Default
#define MOESI_O_Entry NULL
#define MOESI_O_Exit NULL
#define MOESI_DefaultState_MESI coherenceState_MESI
#define MOESI_DefaultState_MESIF coherenceState_MESIF
#define MOESI_DefaultState_MOESI coherenceState_MOESI
#define MOESI_DefaultState_MOSI coherenceState_MOSI
#define MOESI_DefaultState_MSI coherenceState_MSI
#define MOESI_DefaultState_a_del coherenceState_a_del
#define MOESI_DefaultState_a_modify coherenceState_a_modify
#define MOESI_DefaultState_a_read coherenceState_a_read
#define MOESI_DefaultState_i_del coherenceState_i_del
#define MOESI_DefaultState_i_modify coherenceState_i_modify
#define MOESI_DefaultState_i_read coherenceState_i_read

#undef MOESI_I_i_read
#define MOESI_I_i_read MOESI_DefaultState_i_read
#undef MOESI_M_i_read
#define MOESI_M_i_read MOESI_DefaultState_i_read
#undef MOESI_S_i_read
#define MOESI_S_i_read MOESI_DefaultState_i_read
#undef MOESI_E_i_read
#define MOESI_E_i_read MOESI_DefaultState_i_read
#undef MOESI_O_i_read
#define MOESI_O_i_read MOESI_DefaultState_i_read
#undef MOESI_DefaultState_i_read
static void MOESI_DefaultState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.i_read(n, i, l)\n");
    }
}

#undef MOESI_I_i_modify
#define MOESI_I_i_modify MOESI_DefaultState_i_modify
#undef MOESI_M_i_modify
#define MOESI_M_i_modify MOESI_DefaultState_i_modify
#undef MOESI_S_i_modify
#define MOESI_S_i_modify MOESI_DefaultState_i_modify
#undef MOESI_E_i_modify
#define MOESI_E_i_modify MOESI_DefaultState_i_modify
#undef MOESI_O_i_modify
#define MOESI_O_i_modify MOESI_DefaultState_i_modify
#undef MOESI_DefaultState_i_modify
static void MOESI_DefaultState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.i_modify(n, i, l)\n");
    }
}

#undef MOESI_I_i_del
#define MOESI_I_i_del MOESI_DefaultState_i_del
#undef MOESI_M_i_del
#define MOESI_M_i_del MOESI_DefaultState_i_del
#undef MOESI_S_i_del
#define MOESI_S_i_del MOESI_DefaultState_i_del
#undef MOESI_E_i_del
#define MOESI_E_i_del MOESI_DefaultState_i_del
#undef MOESI_O_i_del
#define MOESI_O_i_del MOESI_DefaultState_i_del
#undef MOESI_DefaultState_i_del
static void MOESI_DefaultState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.i_del(n, i, l)\n");
    }
}

#undef MOESI_I_a_read
#define MOESI_I_a_read MOESI_DefaultState_a_read
#undef MOESI_M_a_read
#define MOESI_M_a_read MOESI_DefaultState_a_read
#undef MOESI_S_a_read
#define MOESI_S_a_read MOESI_DefaultState_a_read
#undef MOESI_E_a_read
#define MOESI_E_a_read MOESI_DefaultState_a_read
#undef MOESI_O_a_read
#define MOESI_O_a_read MOESI_DefaultState_a_read
#undef MOESI_DefaultState_a_read
static void MOESI_DefaultState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.a_read(n, i, l)\n");
    }
}

#undef MOESI_I_a_modify
#define MOESI_I_a_modify MOESI_DefaultState_a_modify
#undef MOESI_M_a_modify
#define MOESI_M_a_modify MOESI_DefaultState_a_modify
#undef MOESI_S_a_modify
#define MOESI_S_a_modify MOESI_DefaultState_a_modify
#undef MOESI_E_a_modify
#define MOESI_E_a_modify MOESI_DefaultState_a_modify
#undef MOESI_O_a_modify
#define MOESI_O_a_modify MOESI_DefaultState_a_modify
#undef MOESI_DefaultState_a_modify
static void MOESI_DefaultState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.a_modify(n, i, l)\n");
    }
}

#undef MOESI_I_a_del
#define MOESI_I_a_del MOESI_DefaultState_a_del
#undef MOESI_M_a_del
#define MOESI_M_a_del MOESI_DefaultState_a_del
#undef MOESI_S_a_del
#define MOESI_S_a_del MOESI_DefaultState_a_del
#undef MOESI_E_a_del
#define MOESI_E_a_del MOESI_DefaultState_a_del
#undef MOESI_O_a_del
#define MOESI_O_a_del MOESI_DefaultState_a_del
#undef MOESI_DefaultState_a_del
static void MOESI_DefaultState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_DefaultState.a_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_DefaultState.a_del(n, i, l)\n");
    }
}

#undef MOESI_I_i_modify
static void MOESI_I_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_I)\n");
    }
    if (exist_somewhere() == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_I.i_modify(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_I.i_modify(n, i, l)\n");
        }
        setState(fsm, &MOESI_O);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_I.i_modify(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_I.i_modify(n, i, l)\n");
        }
        setState(fsm, &MOESI_M);
        ENTRY_STATE(getState(fsm));
    }    else {
        MOESI_DefaultState_i_modify(fsm, n, i, l);
    }
}

#undef MOESI_I_i_read
static void MOESI_I_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_I)\n");
    }
    if (exist_somewhere() == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MOESI_S);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MOESI_E);
        ENTRY_STATE(getState(fsm));
    }    else {
        MOESI_DefaultState_i_read(fsm, n, i, l);
    }
}

const struct coherenceState MOESI_I = { POPULATE_STATE(MOESI_I), 12, "MOESI_I" };

#undef MOESI_M_a_modify
static void MOESI_M_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_M.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_M.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_M_a_read
static void MOESI_M_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_M.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_M.a_read(n, i, l)\n");
    }
    setState(fsm, &MOESI_O);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_M_i_del
static void MOESI_M_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_M.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_M.i_del(n, i, l)\n");
    }
    setState(fsm, &MOESI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOESI_M = { POPULATE_STATE(MOESI_M), 13, "MOESI_M" };

#undef MOESI_S_a_del
static void MOESI_S_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_S)\n");
    }
    if (exist_somewhere() == 1 && is_dirty(l) == 1 && exist_state('O') == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_S.a_del(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_S.a_del(n, i, l)\n");
        }
        setState(fsm, &MOESI_O);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0 && is_dirty(l) == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_S.a_del(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_S.a_del(n, i, l)\n");
        }
        setState(fsm, &MOESI_M);
        ENTRY_STATE(getState(fsm));
    }    else {
        MOESI_DefaultState_a_del(fsm, n, i, l);
    }
}

#undef MOESI_S_i_modify
static void MOESI_S_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_S)\n");
    }
    if (exist_somewhere() == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_S.i_modify(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_S.i_modify(n, i, l)\n");
        }
        setState(fsm, &MOESI_O);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_S.i_modify(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_S.i_modify(n, i, l)\n");
        }
        setState(fsm, &MOESI_M);
        ENTRY_STATE(getState(fsm));
    }    else {
        MOESI_DefaultState_i_modify(fsm, n, i, l);
    }
}

const struct coherenceState MOESI_S = { POPULATE_STATE(MOESI_S), 14, "MOESI_S" };

#undef MOESI_E_a_modify
static void MOESI_E_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_E.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_E.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_E_a_read
static void MOESI_E_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_E.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_E.a_read(n, i, l)\n");
    }
    setState(fsm, &MOESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_E_i_del
static void MOESI_E_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_E.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_E.i_del(n, i, l)\n");
    }
    setState(fsm, &MOESI_I);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_E_i_modify
static void MOESI_E_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_E.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_E.i_modify(n, i, l)\n");
    }
    setState(fsm, &MOESI_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOESI_E = { POPULATE_STATE(MOESI_E), 15, "MOESI_E" };

#undef MOESI_O_a_del
static void MOESI_O_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_O)\n");
    }
    if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MOESI_&MOESI_O.a_del(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MOESI_&MOESI_O.a_del(n, i, l)\n");
        }
        setState(fsm, &MOESI_M);
        ENTRY_STATE(getState(fsm));
    }
    else {
        MOESI_DefaultState_a_del(fsm, n, i, l);
    }
}

#undef MOESI_O_a_modify
static void MOESI_O_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_O)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_O.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_O.a_modify(n, i, l)\n");
    }
    setState(fsm, &MOESI_S);
    ENTRY_STATE(getState(fsm));
}

#undef MOESI_O_i_del
static void MOESI_O_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MOESI_O)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MOESI_&MOESI_O.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MOESI_&MOESI_O.i_del(n, i, l)\n");
    }
    setState(fsm, &MOESI_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MOESI_O = { POPULATE_STATE(MOESI_O), 16, "MOESI_O" };

#define MESIF_I_MESI coherenceState_MESI
#define MESIF_I_MESIF coherenceState_MESIF
#define MESIF_I_MOESI coherenceState_MOESI
#define MESIF_I_MOSI coherenceState_MOSI
#define MESIF_I_MSI coherenceState_MSI
#define MESIF_I_a_del coherenceState_a_del
#define MESIF_I_a_modify coherenceState_a_modify
#define MESIF_I_a_read coherenceState_a_read
#define MESIF_I_i_del coherenceState_i_del
#define MESIF_I_i_modify coherenceState_i_modify
#define MESIF_I_i_read coherenceState_i_read
#define MESIF_I_Default coherenceState_Default
#define MESIF_I_Entry NULL
#define MESIF_I_Exit NULL
#define MESIF_M_MESI coherenceState_MESI
#define MESIF_M_MESIF coherenceState_MESIF
#define MESIF_M_MOESI coherenceState_MOESI
#define MESIF_M_MOSI coherenceState_MOSI
#define MESIF_M_MSI coherenceState_MSI
#define MESIF_M_a_del coherenceState_a_del
#define MESIF_M_a_modify coherenceState_a_modify
#define MESIF_M_a_read coherenceState_a_read
#define MESIF_M_i_del coherenceState_i_del
#define MESIF_M_i_modify coherenceState_i_modify
#define MESIF_M_i_read coherenceState_i_read
#define MESIF_M_Default coherenceState_Default
#define MESIF_M_Entry NULL
#define MESIF_M_Exit NULL
#define MESIF_S_MESI coherenceState_MESI
#define MESIF_S_MESIF coherenceState_MESIF
#define MESIF_S_MOESI coherenceState_MOESI
#define MESIF_S_MOSI coherenceState_MOSI
#define MESIF_S_MSI coherenceState_MSI
#define MESIF_S_a_del coherenceState_a_del
#define MESIF_S_a_modify coherenceState_a_modify
#define MESIF_S_a_read coherenceState_a_read
#define MESIF_S_i_del coherenceState_i_del
#define MESIF_S_i_modify coherenceState_i_modify
#define MESIF_S_i_read coherenceState_i_read
#define MESIF_S_Default coherenceState_Default
#define MESIF_S_Entry NULL
#define MESIF_S_Exit NULL
#define MESIF_E_MESI coherenceState_MESI
#define MESIF_E_MESIF coherenceState_MESIF
#define MESIF_E_MOESI coherenceState_MOESI
#define MESIF_E_MOSI coherenceState_MOSI
#define MESIF_E_MSI coherenceState_MSI
#define MESIF_E_a_del coherenceState_a_del
#define MESIF_E_a_modify coherenceState_a_modify
#define MESIF_E_a_read coherenceState_a_read
#define MESIF_E_i_del coherenceState_i_del
#define MESIF_E_i_modify coherenceState_i_modify
#define MESIF_E_i_read coherenceState_i_read
#define MESIF_E_Default coherenceState_Default
#define MESIF_E_Entry NULL
#define MESIF_E_Exit NULL
#define MESIF_F_MESI coherenceState_MESI
#define MESIF_F_MESIF coherenceState_MESIF
#define MESIF_F_MOESI coherenceState_MOESI
#define MESIF_F_MOSI coherenceState_MOSI
#define MESIF_F_MSI coherenceState_MSI
#define MESIF_F_a_del coherenceState_a_del
#define MESIF_F_a_modify coherenceState_a_modify
#define MESIF_F_a_read coherenceState_a_read
#define MESIF_F_i_del coherenceState_i_del
#define MESIF_F_i_modify coherenceState_i_modify
#define MESIF_F_i_read coherenceState_i_read
#define MESIF_F_Default coherenceState_Default
#define MESIF_F_Entry NULL
#define MESIF_F_Exit NULL
#define MESIF_DefaultState_MESI coherenceState_MESI
#define MESIF_DefaultState_MESIF coherenceState_MESIF
#define MESIF_DefaultState_MOESI coherenceState_MOESI
#define MESIF_DefaultState_MOSI coherenceState_MOSI
#define MESIF_DefaultState_MSI coherenceState_MSI
#define MESIF_DefaultState_a_del coherenceState_a_del
#define MESIF_DefaultState_a_modify coherenceState_a_modify
#define MESIF_DefaultState_a_read coherenceState_a_read
#define MESIF_DefaultState_i_del coherenceState_i_del
#define MESIF_DefaultState_i_modify coherenceState_i_modify
#define MESIF_DefaultState_i_read coherenceState_i_read

#undef MESIF_I_i_read
#define MESIF_I_i_read MESIF_DefaultState_i_read
#undef MESIF_M_i_read
#define MESIF_M_i_read MESIF_DefaultState_i_read
#undef MESIF_S_i_read
#define MESIF_S_i_read MESIF_DefaultState_i_read
#undef MESIF_E_i_read
#define MESIF_E_i_read MESIF_DefaultState_i_read
#undef MESIF_F_i_read
#define MESIF_F_i_read MESIF_DefaultState_i_read
#undef MESIF_DefaultState_i_read
static void MESIF_DefaultState_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.i_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.i_read(n, i, l)\n");
    }
}

#undef MESIF_I_i_modify
#define MESIF_I_i_modify MESIF_DefaultState_i_modify
#undef MESIF_M_i_modify
#define MESIF_M_i_modify MESIF_DefaultState_i_modify
#undef MESIF_S_i_modify
#define MESIF_S_i_modify MESIF_DefaultState_i_modify
#undef MESIF_E_i_modify
#define MESIF_E_i_modify MESIF_DefaultState_i_modify
#undef MESIF_F_i_modify
#define MESIF_F_i_modify MESIF_DefaultState_i_modify
#undef MESIF_DefaultState_i_modify
static void MESIF_DefaultState_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.i_modify(n, i, l)\n");
    }
}

#undef MESIF_I_i_del
#define MESIF_I_i_del MESIF_DefaultState_i_del
#undef MESIF_M_i_del
#define MESIF_M_i_del MESIF_DefaultState_i_del
#undef MESIF_S_i_del
#define MESIF_S_i_del MESIF_DefaultState_i_del
#undef MESIF_E_i_del
#define MESIF_E_i_del MESIF_DefaultState_i_del
#undef MESIF_F_i_del
#define MESIF_F_i_del MESIF_DefaultState_i_del
#undef MESIF_DefaultState_i_del
static void MESIF_DefaultState_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.i_del(n, i, l)\n");
    }
}

#undef MESIF_I_a_read
#define MESIF_I_a_read MESIF_DefaultState_a_read
#undef MESIF_M_a_read
#define MESIF_M_a_read MESIF_DefaultState_a_read
#undef MESIF_S_a_read
#define MESIF_S_a_read MESIF_DefaultState_a_read
#undef MESIF_E_a_read
#define MESIF_E_a_read MESIF_DefaultState_a_read
#undef MESIF_F_a_read
#define MESIF_F_a_read MESIF_DefaultState_a_read
#undef MESIF_DefaultState_a_read
static void MESIF_DefaultState_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.a_read(n, i, l)\n");
    }
}

#undef MESIF_I_a_modify
#define MESIF_I_a_modify MESIF_DefaultState_a_modify
#undef MESIF_M_a_modify
#define MESIF_M_a_modify MESIF_DefaultState_a_modify
#undef MESIF_S_a_modify
#define MESIF_S_a_modify MESIF_DefaultState_a_modify
#undef MESIF_E_a_modify
#define MESIF_E_a_modify MESIF_DefaultState_a_modify
#undef MESIF_F_a_modify
#define MESIF_F_a_modify MESIF_DefaultState_a_modify
#undef MESIF_DefaultState_a_modify
static void MESIF_DefaultState_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.a_modify(n, i, l)\n");
    }
}

#undef MESIF_I_a_del
#define MESIF_I_a_del MESIF_DefaultState_a_del
#undef MESIF_M_a_del
#define MESIF_M_a_del MESIF_DefaultState_a_del
#undef MESIF_S_a_del
#define MESIF_S_a_del MESIF_DefaultState_a_del
#undef MESIF_E_a_del
#define MESIF_E_a_del MESIF_DefaultState_a_del
#undef MESIF_F_a_del
#define MESIF_F_a_del MESIF_DefaultState_a_del
#undef MESIF_DefaultState_a_del
static void MESIF_DefaultState_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_DefaultState)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_DefaultState.a_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_DefaultState.a_del(n, i, l)\n");
    }
}

#undef MESIF_I_i_modify
static void MESIF_I_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_I)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_I.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_I.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_M);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_I_i_read
static void MESIF_I_i_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_I)\n");
    }
    if (exist_state('E') == 1 || exist_state('M') == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MESIF_F);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_state('F') == 1) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MESIF_S);
        ENTRY_STATE(getState(fsm));
    }
    else if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESIF_&MESIF_I.i_read(n, i, l)\n");
        }
        setState(fsm, &MESIF_E);
        ENTRY_STATE(getState(fsm));
    }    else {
        MESIF_DefaultState_i_read(fsm, n, i, l);
    }
}

const struct coherenceState MESIF_I = { POPULATE_STATE(MESIF_I), 17, "MESIF_I" };

#undef MESIF_M_a_modify
static void MESIF_M_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_M.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_M.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_M_a_read
static void MESIF_M_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_M.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_M.a_read(n, i, l)\n");
    }
    setState(fsm, &MESIF_S);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_M_i_del
static void MESIF_M_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_M)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_M.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_M.i_del(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESIF_M = { POPULATE_STATE(MESIF_M), 18, "MESIF_M" };

#undef MESIF_S_a_del
static void MESIF_S_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_S)\n");
    }
    if (exist_state('S') == 1 && exist_state('F') == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESIF_&MESIF_S.a_del(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESIF_&MESIF_S.a_del(n, i, l)\n");
        }
        setState(fsm, &MESIF_F);
        ENTRY_STATE(getState(fsm));
    }
    else {
        MESIF_DefaultState_a_del(fsm, n, i, l);
    }
}

#undef MESIF_S_i_del
static void MESIF_S_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_S.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_S.i_del(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_S_i_modify
static void MESIF_S_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_S)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_S.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_S.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESIF_S = { POPULATE_STATE(MESIF_S), 19, "MESIF_S" };

#undef MESIF_E_a_modify
static void MESIF_E_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_E.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_E.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_E_a_read
static void MESIF_E_a_read(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_E.a_read(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_E.a_read(n, i, l)\n");
    }
    setState(fsm, &MESIF_S);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_E_i_del
static void MESIF_E_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_E.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_E.i_del(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_E_i_modify
static void MESIF_E_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_E)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_E.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_E.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESIF_E = { POPULATE_STATE(MESIF_E), 20, "MESIF_E" };

#undef MESIF_F_a_del
static void MESIF_F_a_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_F)\n");
    }
    if (exist_somewhere() == 0) {
        EXIT_STATE(getState(fsm));
        if (getDebugFlag(fsm) != 0) {
            TRACE("ENTER TRANSITION: MESIF_&MESIF_F.a_del(n, i, l)\n");
        }
        /* No actions. */
        if (getDebugFlag(fsm) != 0) {
            TRACE("EXIT TRANSITION : MESIF_&MESIF_F.a_del(n, i, l)\n");
        }
        setState(fsm, &MESIF_E);
        ENTRY_STATE(getState(fsm));
    }
    else {
        MESIF_DefaultState_a_del(fsm, n, i, l);
    }
}

#undef MESIF_F_a_modify
static void MESIF_F_a_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_F)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_F.a_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_F.a_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_F_i_del
static void MESIF_F_i_del(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_F)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_F.i_del(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_F.i_del(n, i, l)\n");
    }
    setState(fsm, &MESIF_I);
    ENTRY_STATE(getState(fsm));
}

#undef MESIF_F_i_modify
static void MESIF_F_i_modify(struct coherenceContext *fsm, struct node* n, unsigned long i, struct line* l)
{

    if (getDebugFlag(fsm) != 0) {
        TRACE("LEAVING STATE   : MESIF_F)\n");
    }
    EXIT_STATE(getState(fsm));
    if (getDebugFlag(fsm) != 0) {
        TRACE("ENTER TRANSITION: MESIF_&MESIF_F.i_modify(n, i, l)\n");
    }
    if (getDebugFlag(fsm) != 0) {
        TRACE("EXIT TRANSITION : MESIF_&MESIF_F.i_modify(n, i, l)\n");
    }
    setState(fsm, &MESIF_M);
    ENTRY_STATE(getState(fsm));
}

const struct coherenceState MESIF_F = { POPULATE_STATE(MESIF_F), 21, "MESIF_F" };

#ifdef NO_COHERENCE_SM_MACRO
void coherenceContext_Init(struct coherenceContext* fsm, struct coherence* owner)
{
    FSM_INIT(fsm, &Init_Start);
    fsm->_owner = owner;
}

void coherenceContext_MESI(struct coherenceContext* fsm)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "MESI");
    state->MESI(fsm);
    setTransition(fsm, NULL);
}

void coherenceContext_MESIF(struct coherenceContext* fsm)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "MESIF");
    state->MESIF(fsm);
    setTransition(fsm, NULL);
}

void coherenceContext_MOESI(struct coherenceContext* fsm)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "MOESI");
    state->MOESI(fsm);
    setTransition(fsm, NULL);
}

void coherenceContext_MOSI(struct coherenceContext* fsm)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "MOSI");
    state->MOSI(fsm);
    setTransition(fsm, NULL);
}

void coherenceContext_MSI(struct coherenceContext* fsm)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "MSI");
    state->MSI(fsm);
    setTransition(fsm, NULL);
}

void coherenceContext_a_del(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "a_del");
    state->a_del(fsm, n, i, l);
    setTransition(fsm, NULL);
}

void coherenceContext_a_modify(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "a_modify");
    state->a_modify(fsm, n, i, l);
    setTransition(fsm, NULL);
}

void coherenceContext_a_read(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "a_read");
    state->a_read(fsm, n, i, l);
    setTransition(fsm, NULL);
}

void coherenceContext_i_del(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "i_del");
    state->i_del(fsm, n, i, l);
    setTransition(fsm, NULL);
}

void coherenceContext_i_modify(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "i_modify");
    state->i_modify(fsm, n, i, l);
    setTransition(fsm, NULL);
}

void coherenceContext_i_read(struct coherenceContext* fsm, struct node* n, unsigned long i, struct line* l)
{
    const struct coherenceState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "i_read");
    state->i_read(fsm, n, i, l);
    setTransition(fsm, NULL);
}
#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
