.TH CASSIS "7" "12/03/2014" "CASSIS 1.0.0" "Architecture configuration"
.SH NAME
cassis \- documentation about architecture configuration for cassis
.SH DESCRIPTION
An execution of Cassis on a xml file produced by hwloc (lstopo --of xml file.xml) will create a file file.cassis.xml which describes all the parameters for the architecture. Then you can directly execute Cassis on the .cassis.xml file. You can modify the .cassis.xml file as you will to simulate the architecture you want. Therefore it is advised to begin by generating an xml file with hwloc, then run Cassis on that file, and from that point on work only with the .cassis.xml file.
.SH FILE DESCRIPTION
\fB\<Architecture>: decribes global information concerning the architecture
.SH ""
	* name: name of the architecture
.SH ""
	* CPU_name: name of the CPU
.SH ""
	* number_levels: number of levels if the cache hierarchy
.TP
\fB\<Level>: parameters shared with a cache level
.TP
.sh ""
	* depth: depth of the level
.TP
.sh ""
	* coherence_protocol (not for last level): MSI or MESI
.TP
.sh ""
	* type (not for L1): inclusive, exclusive, nieo (Not Inclusive Exclusive Oriented) or niio (Not Inclusive Inclusive Oriented).
.TP
.sh ""
	* snooping (not for last level): true or false
.TP
.sh ""
	* directory_manager (note for L1): true or false
.TP
\fB\<Cache>: parameters specific to a cache
.TP
.sh ""
	* depth: depth of the cache
.TP
.sh ""
	* cache_size: size of the cache (in bytes)
.TP
.sh ""
	* cache_linesize: size of a line in the cache (in bytes)
.TP
.sh ""
	* cache_associativity: associativity of the cache
.TP
.sh ""
	* replacement_protocol: LRU, LFU or FIFO
.SH "EXAMPLE"
<?xml version="1.0"?>
<Architecture name="x86_64" CPU_name="Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (modified)" number_levels="3">
  <Level depth="3" type="inclusive" directory_manager="false"/>
  <Level depth="2" coherence_protocol="MESI" type="inclusive" snooping="true" directory_manager="false"/>
  <Level depth="1" coherence_protocol="MESI" snooping="true"/>
  <Cache depth="3" cache_size="3145728" cache_linesize="64" cache_associativity="12" replacement_protocol="LRU">
    <Cache depth="2" cache_size="262144" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU">
      <Cache depth="1" cache_size="32768" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU"/>
      <Cache depth="1" cache_size="32768" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU"/>
    </Cache>
    <Cache depth="2" cache_size="262144" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU">
      <Cache depth="1" cache_size="32768" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU"/>
      <Cache depth="1" cache_size="32768" cache_linesize="64" cache_associativity="8" replacement_protocol="LRU"/>
    </Cache>
  </Cache>
</Architecture>
.SH AUTHORS
Written by the CASSIS team at ENSEIRB-Matmeca, FRANCE. The team was composed of Nicolas Dubois, Pierre Goudet, Nicolas Heng, Alexandre Horonat, Gilles Marait, Grégoire Pichon.
.SH "SEE ALSO"
cassis(1), lstopo(1)
